// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaDePermissao.Data;

namespace SistemaDePermissao.Migrations
{
    [DbContext(typeof(SistemaDePermissaoContext))]
    [Migration("20211104234938_migration2")]
    partial class migration2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SistemaDePermissao.Models.links", b =>
                {
                    b.Property<int>("LinksID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("dataatualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("datacadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("descricao")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("LinksID");

                    b.ToTable("links");
                });

            modelBuilder.Entity("SistemaDePermissao.Models.permissao", b =>
                {
                    b.Property<int>("PermissaoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("LinksID")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.Property<DateTime>("dataatualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("datacadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("descricao")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("PermissaoID");

                    b.HasIndex("LinksID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("permissao");
                });

            modelBuilder.Entity("SistemaDePermissao.Models.usuario", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("cargo")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("dataatualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("datacadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("UsuarioID");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("SistemaDePermissao.Models.permissao", b =>
                {
                    b.HasOne("SistemaDePermissao.Models.links", "Links")
                        .WithMany()
                        .HasForeignKey("LinksID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaDePermissao.Models.usuario", "Usario")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
