// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaDePermissao.Data;

namespace SistemaDePermissao.Migrations
{
    [DbContext(typeof(SistemaDePermissaoContext))]
    [Migration("20211126040916_migration7")]
    partial class migration7
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SistemaDePermissao.Models.TipoDeUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descriçao")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("TipoDeUsuario");
                });

            modelBuilder.Entity("SistemaDePermissao.Models.links", b =>
                {
                    b.Property<int>("LinksID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("descricao")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("tipoDeUsuarioId")
                        .HasColumnType("int");

                    b.HasKey("LinksID");

                    b.HasIndex("tipoDeUsuarioId");

                    b.ToTable("links");
                });

            modelBuilder.Entity("SistemaDePermissao.Models.usuario", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("cargo")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("flag")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("senha")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("tipoDeUsuarioId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioID");

                    b.HasIndex("tipoDeUsuarioId");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("SistemaDePermissao.Models.links", b =>
                {
                    b.HasOne("SistemaDePermissao.Models.TipoDeUsuario", "tipoDeUsuario")
                        .WithMany()
                        .HasForeignKey("tipoDeUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaDePermissao.Models.usuario", b =>
                {
                    b.HasOne("SistemaDePermissao.Models.TipoDeUsuario", "tipoDeUsuario")
                        .WithMany()
                        .HasForeignKey("tipoDeUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
